// AUTO-GENERATED by scripts/generate-build-meta.cjs
export const BUILD_COMMIT = '03825ecee462e7c93e7b65fc1864ad1fe851bedf';
export const BUILD_COMMIT_SHORT = '03825ec';
export const BUILD_DATE_ISO = '2025-09-18T02:48:57.702Z';
