// AUTO-GENERATED by scripts/generate-build-meta.cjs
export const BUILD_COMMIT = '9a3aeec9f5ac9c0a8fe81fd08cd38c06512737b4';
export const BUILD_COMMIT_SHORT = '9a3aeec';
export const BUILD_DATE_ISO = '2025-09-19T04:01:24.472Z';
