// AUTO-GENERATED by scripts/generate-build-meta.cjs
export const BUILD_COMMIT = 'c5310f706f993288ecf3b11cc4f8345e6e6b3a7c';
export const BUILD_COMMIT_SHORT = 'c5310f7';
export const BUILD_DATE_ISO = '2025-09-19T04:23:01.800Z';
